# Generated by Django 6.0.3 on 2026-03-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL别名")),
            ],
            options={
                "verbose_name": "视频分类",
                "verbose_name_plural": "视频分类",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "cover",
                    models.ImageField(upload_to="covers/", verbose_name="封面图"),
                ),
                (
                    "video_file",
                    models.FileField(upload_to="videos/", verbose_name="视频文件"),
                ),
                ("description", models.TextField(verbose_name="简介")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="播放量"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.videocategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频",
                "verbose_name_plural": "视频",
            },
        ),
    ]
